### ISSUE TITLE
Tokens do not seem to refresh automatically.

### ISSUE THREAD

**Issue by MaxxDelusional** [pimmerks/SpotifyWebApi#13]
The Token's TokenGenerated property is set in the constructor, but the property is not serializable to json.

When deserializing a Token from json, the property will have the current date instead of the date it was actually generated. This causes the IsExpired flag to be false, when it should be true.

**Comment by pimmerks** [comment]
Looks like just adding the `[JsonProperty("token_generated")]` attribute to the `TokenGenerated` property fixes this, will be added in the next release!

**Comment by MaxxDelusional** [comment]
It may not be enough to just add this attribute. The `IsExpired` flag would have the correct value, but I don't see anything in ApiClient that actually updates the token using the refresh_token.

I tried setting the `TokenGenerated` property through reflection, but I still found that the tokens weren't refreshing automatically.

**Comment by pimmerks** [comment]
Ah that's true right now however I have added a `AuthorizationCode.RefreshToken(...)` function in the new pull request [here](https://github.com/pimmerks/SpotifyWebApi/pull/12/files#diff-042a06876be1cae21e008f90297afcacR102).

Although I'm still not sure if the ApiClient should validate tokens and refresh tokens, or let the user's of the library validate tokens themselfs.
