### ISSUE TITLE
GetMyPlaylists doesnt work

### ISSUE THREAD

**Issue by SenfTorte** [pimmerks/SpotifyWebApi#21]
The GetMyPlaylists function doesnt work correctly. Ive got the following error message:
Error converting value "spotify:playlist:3G1AlVTYExPN28BlCxf8GD" to type 'SpotifyWebApi.Model.Uri.SpotifyUri'. Path 'items[0].uri', line 34, position 53.

**Comment by pimmerks** [comment]
Hmm it looks like Spotify changed their playlist uri format, will fix this as soon as I have time!
