### ISSUE TITLE
I can only get the first 100 songs of a playlist

### ISSUE THREAD

**Issue by sahin-a** [pimmerks/SpotifyWebApi#30]
I can only ge tthe first 100 songs of any playlist

            FullPlaylist playlist = spotify.Playlist.GetPlaylist(uri).Result;

**Comment by pimmerks** [comment]
Hi,

To receive playlist tracks you should call the `IPlaylistApi.GetPlaylistTracks(playlistUri);` function.
Here you can provide optional offset and limit parameters. Note that Spotify only allows a maximum of 100 songs to be received per request.
See here: https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-playlists-tracks
